from .pubmed import query_pubmed
from .oxford_academic import scrape_quarterly_journal_of_economics, scrape_review_of_financial_studies
from .american_economic import scrape_american_economics_review
from .american_accounting import scrape_accounting_review
from .wiley import scrape_journal_of_finance